version: '3.9'

services:
  postgres:
    image: nexus.sogaz.ru/postgres:16
    container_name: shedlock_postgres
    environment:
      POSTGRES_DB: payment_receipt_service_db
      POSTGRES_USER: payment_receipt_user
      POSTGRES_PASSWORD: payment_receipt_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shedlock-net

  # Билдим один раз образ сервиса
  payment-service-build:
    build: .
    image: payment-receipt-service-local
    networks:
      - shedlock-net

  # Инстанс №1 — с Liquibase
  payment-service-1:
    image: payment-receipt-service-local
    container_name: payment-receipt-service-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_receipt_service_db
      SPRING_DATASOURCE_USERNAME: payment_receipt_user
      SPRING_DATASOURCE_PASSWORD: payment_receipt_pass
      SPRING_PROFILES_ACTIVE: local
      SPRING_LIQUIBASE_ENABLED: "true"
    depends_on:
      - postgres
      - payment-service-build
    networks:
      - shedlock-net

  # Инстанс №2 — без Liquibase
  payment-service-2:
    image: payment-receipt-service-local
    container_name: payment-receipt-service-2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_receipt_service_db
      SPRING_DATASOURCE_USERNAME: payment_receipt_user
      SPRING_DATASOURCE_PASSWORD: payment_receipt_pass
      SPRING_PROFILES_ACTIVE: local
      SPRING_LIQUIBASE_ENABLED: "false"
    depends_on:
      - postgres
      - payment-service-build
    networks:
      - shedlock-net

  # Инстанс №3 — без Liquibase
  payment-service-3:
    image: payment-receipt-service-local
    container_name: payment-receipt-service-3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_receipt_service_db
      SPRING_DATASOURCE_USERNAME: payment_receipt_user
      SPRING_DATASOURCE_PASSWORD: payment_receipt_pass
      SPRING_PROFILES_ACTIVE: local
      SPRING_LIQUIBASE_ENABLED: "false"
    depends_on:
      - postgres
      - payment-service-build
    networks:
      - shedlock-net

networks:
  shedlock-net:

volumes:
  pgdata: