app:
  info:
    application_name: ${PROJECT_NAME:app service}
    version: ${PROJECT_VERSION:1.0.0}
    description: ${PROJECT_DESCRIPTION:Payment Receipt Service}
    artifact_Id: ${PROJECT_ARTIFACTID:payment-receipt-service}
    group_Id: ${PROJECT_GROUPID:ru.sogaz.site}
    app_profile: ${ENVIRONMENT:dev}
    java-version: ${JAVA_VERSION:21}

server:
  port: ${SERVER_PORT:8080}
  use-forward-headers: true
  forward-headers-strategy: framework
  main.allow-bean-definition-overriding: true

spring:
  application:
    name: payment-receipt-service
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/receipt}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${HOSTNAME:localhost}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_SERVER_PORT:8091}
  health:
    livenessState:
      enable: true
    readinessState:
      enable: true

logging:
  level:
    ru:
      sogaz:
        site:
          pattern: ${LOGGING_LEVEL_RU_SOGAZ_ESB:DEBUG}
  proxy:
    frontend-enabled: ${LOGGING_PROXY_FRONTEND_ENABLED:true}
    upstream-enabled: ${LOGGING_PROXY_UPSTREAM_ENABLED:true}
    max-body-bytes: ${LOGGING_PROXY_MAX_BODY_BYTES:6000}
    log-headers: ${LOGGING_PROXY_LOG_HEADERS:false}
    stacktrace-enabled: ${LOGGING_PROXY_STACKTRACE_ENABLE:false}
    sensitive-fields: ${LOGGING_SENSITIVE_FIELDS}

  rabbit:
    enabled: ${LOGGING_RABBIT_ENABLED:true}
    log-body: ${LOGGING_RABBIT_LOG_BODY:true}
    confirms-enabled: ${LOGGING_RABBIT_CONFIRMS_ENABLED:true}
    returns-enabled: ${LOGGING_RABBIT_RETURNS_ENABLED:true}

logstash:
  host: ${LOG_SERVER_HOST:log.sogaz.ru}
  port: ${LOG_SERVER_PORT:12201}
  level: ${LOG_LEVEL:INFO}
  level_test: ${LOG_LEVEL_TEST:INFO}

config:
  atolURL: ${ATOL_URL:https://testonline.atol.ru/possystem}
  AtolLogin: ${ATOL_LOGIN:v4-online-atol-ru}
  AtolPass: ${ATOL_PASS:iGFFuihss}
  tokenTime: ${TOKEN_TIME:720}
  callbackURL: ${CALLBACK_URL:http://localhost:8080/paymentCheck/status}
  companyEmail: ${COMPANY_EMAIL:Diop.Sheykh@sogaz.ru}
  companyInn: ${COMPANY_INN:5544332219}
  paymentAddress: ${PAYMENT_ADDRESS:https://your-payment.url}
  groupCode: ${GROUP_CODE:v4-online-atol-ru_4179}
  periodStatusUpdate: ${PERIOD_STATUS_UPDATE:10}

scheduled:
  task:
    defaultDelay: ${CHECK_STATUS_DELAY:60000}